# Generated by Django 5.1.6 on 2025-02-18 08:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_band_active_band_biography_band_genre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='_type',
            field=models.CharField(choices=[('RC', 'Records'), ('CL', 'Clothing'), ('PT', 'Posters'), ('MC', 'Miscellaneous')], default='MC', max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listing',
            name='decription',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listing',
            name='sold',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listing',
            name='year',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
