# Generated by Django 5.1.6 on 2025-02-19 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_listing_band'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='_type',
            new_name='type_e',
        ),
    ]
